apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-0iek
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-0iek
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-0iek
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-0iek
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-0iek
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-dies-tenant/rhtap-demo-app/hacbs-test-project-0iek@sha256:581daa6b057cadfbe69ee355ee87567fc44d802c550445fd3e0701a0e0ede02b
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
